config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    registrations: 'admin_users/registrations'
  }


  # backend: area for admin users
  namespace :backend do
    root to: 'dashboards#index'
    resources :dashboards, only: [] do
      collection do
        get :administration
      end
    end
    resources :admin_users
    resources :appointments
    resources :change_requests, only: [:index]
    resources :competitions
    resources :competition_files
    resources :events
    resources :group_scores
    resources :group_score_categories
    resources :group_score_types
    resources :imports, only: [:index]
    resources :import_requests
    resources :links
    resources :nations
    resources :news
    resources :people
    resources :person_participations
    resources :person_spellings
    resources :places
    resources :repairs, only: [] do
      collection do
        get :teams
      end
    end
    resources :scores
    resources :score_types
    namespace :series do
      resources :rounds, only: [:new, :create, :show, :index] do 
        member do
          post ':cup_id/destroy', action: :competition_destroy
        end
      end
    end
    resources :teams
  end

  # api for interacting with ajax requests
  namespace :api do
    resources :api_users, only: [:create] do
      collection do
        post :status
        post :logout
      end
    end
    resources :appointments, only: [:create, :show, :update]
    resources :change_requests, only: [:create, :index, :update] do
      resources :files, only: [:show], to: 'change_requests#files'
    end
    resources :competitions, only: [:create, :show, :index, :update] do
      member { post :files }
    end
    resources :events, only: [:create, :show, :index]
    resources :group_score_types, only: [:create, :index]
    resources :group_score_categories, only: [:create, :index]
    resources :group_scores, only: [:show, :update] do
      member { put :person_participation }
    end
    resources :imports, only: [] do
      collection do 
        post :check_lines
        post :scores
      end
    end
    resources :links, only: [:create, :show, :destroy]
    resources :nations, only: [:show, :index]
    resources :people, only: [:create, :show, :index, :update] do
      member { post :merge }
    end
    resources :person_spellings, only: [:index]
    resources :places, only: [:create, :show, :index, :update]
    resources :score_types, only: [:index]
    resources :scores, only: [:show, :update]
    namespace :series do
      resources :assessments, only: [:index]
      resources :cups, only: [:index]
      resources :participations, only: [:create, :show, :index, :update, :destroy]
      resources :rounds, only: [:index]
      resources :team_assessments, only: [:index]
    end
    resources :suggestions, only: [] do
      collection do
        post :people
        post :teams
      end
    end
    resources :team_members, only: [:index]
    resources :team_spellings, only: [:index]
    resources :teams, only: [:create, :show, :index, :update] do
      member { post :merge }
    end
  end

  namespace :comp_reg do
    resources :competitions do
      collection { get :new_select_template }
      member { get :publishing }
      scope module: :competitions do
        resource :mail, only: [:new, :create]
      end
    end
    resources :teams, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :people, only: [:new, :create, :edit, :update, :destroy] do
      member do
        get :participations
      end
    end
  end

  get 'wa/:slug', to: 'comp_reg/competitions#slug_handle', as: :comp_reg_slug

  # following controllers will write html cache
  resources :change_logs, only: [:index, :show]
  resources :appointments, only: [:index, :show]
  resources :competitions, only: [:index, :show]
  resources :people, only: [:index, :show]
  resources :places, only: [:index, :show]
  resources :teams, only: [:index, :show]
  resources :news, only: [:index, :show]
  resources :years, only: [:index, :show] do
    member do
      get :best_performance
      get :best_scores
    end
  end
  resources :events, only: [:index, :show]
  namespace :series do
    resources :rounds, only: [:index, :show]
    resources :assessments, only: [:show]
  end
  scope :images do
    get 'person_la_positions/:person_id', controller: :images, action: :la_positions, as: :images_person_la_positions
  end

  get :rss, to: 'pages#rss'
  get :impressum, to: 'pages#legal_notice'
  get :feuerwehrsport, to: 'pages#firesport_overview'
  get :wettkampf_manager, to: 'pages#wettkampf_manager'
  get :online_anmeldungen, to: 'pages#online_anmeldungen'
  get :last_competitions, to: 'pages#last_competitions_overview'
  get :records, to: 'pages#records'
  get :best_of, to: 'pages#best_of'
  root to: 'pages#dashboard'

  # error handling
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/models/calculation/performance_of_year/team.rb
module Calculation
  module PerformanceOfYear
    class Team < Base
      def team
        entity
      end

      def self.score_collection
        GroupScore.regular.includes(group_score_category: { competition: [:event, :place] }).includes(:team)
      end
    end
  end
end

app/models/comp_reg.rb
module CompReg
  def self.table_name_prefix
    'comp_reg_'
  end
end

app/models/comp_reg/assessment_participation.rb
module CompReg
  class AssessmentParticipation < ActiveRecord::Base
    belongs_to :competition_assessment

    validates :competition_assessment, presence: true
  end
end

app/models/comp_reg/competitions.rb
module CompReg::Competitions
  def self.table_name_prefix
    'comp_reg_competitions_'
  end
end

app/models/comp_reg/competitions/mail.rb
class CompReg::Competitions::Mail < ActiveRecord::Base
  belongs_to :competition, class_name: 'CompReg::Competition'
  belongs_to :admin_user

  validates :subject, :text, presence: true
end

app/controllers/api/teams_controller.rb
module API
  class TeamsController < BaseController
    include CRUD::CreateAction
    include CRUD::ShowAction
    include CRUD::UpdateAction
    include CRUD::IndexAction
    include CRUD::ChangeLogSupport
    include MergeAction

    protected

    def resource_instance_show_object
      params[:extended].present? ? ExtendedTeamSerializer.new(resource_instance) : super
    end

    def create_permitted_attributes
      permitted_attributes.permit(:name, :shortcut, :status)
    end

    def update_permitted_attributes
      permitted_keys = [:latitude, :longitude, :state]
      permitted_keys.push(:name, :shortcut, :status, :image_change_request) if can?(:correct, resource_instance.object)
      permitted_attributes.permit(*permitted_keys)
    end
  end
end

app/controllers/backend/teams_controller.rb
module Backend
  class TeamsController < ResourcesController
    protected

    def permitted_attributes
      super.permit(:name, :shortcut, :status, :latitude, :longitude, :image, :state)
    end
  end
end

app/controllers/comp_reg/comp_reg_controller.rb
module CompReg
  class CompRegController < ApplicationController
    include ResourceAccessor

    # before_action :authenticate_admin_user!
    # before_action :ensure_user_signed_in
    protect_from_forgery with: :exception

    protected

    def clean_cache?(action_name)
      false
    end

    def current_user
      current_admin_user
    end
  end
end

app/controllers/comp_reg/competitions/mails_controller.rb
class CompReg::Competitions::MailsController < CompReg::CompRegController
  include CRUD::NewAction
  include CRUD::CreateAction

  protected

  def resource_class
    CompReg::Competitions::Mail
  end

  def build_instance
    resource_class.new(admin_user: current_admin_user, competition: competition)
  end

  def competition
    CompReg::Competition.find(params[:competition_id])
  end

  def permitted_attributes
    super.permit(:subject, :text, :add_registration_file)
  end

  def before_create_success
    flash[:success] = 'E-Mail wird im Hintergrund versendet'

    resource_instance.object.competition.teams.each do |team|
      deliver(CompReg::CompetitionMailer, :team_news, resource_instance, team)
    end

    resource_instance.object.competition.people.where(team_id: nil).each do |person|
      deliver(CompReg::CompetitionMailer, :person_news, resource_instance, person)
    end

    redirect_to competition
  end
end

app/controllers/comp_reg/competitions_controller.rb
module CompReg
  class CompetitionsController < CompRegController
    include CRUD::NewAction
    include CRUD::CreateAction
    include CRUD::ShowAction
    include CRUD::IndexAction
    include CRUD::EditAction
    include CRUD::UpdateAction
    include CRUD::DestroyAction

    before_action :assign_instance_for_edit, only: [:edit, :publishing]

    def publishing
      resource_instance.slug = resource_instance.to_s.parameterize if resource_instance.slug.blank?
    end

    def new_select_template
      la = build_instance.decorate
      la.name = "Löschangriff-Wettkampf"
      la.competition_assessments.build(discipline: :la, gender: :male)
      la.competition_assessments.build(discipline: :la, gender: :female)

      la_youth = build_instance.decorate
      la_youth.name = "Löschangriff-Wettkampf mit Jugend"
      la_youth.competition_assessments.build(discipline: :la, gender: :male)
      la_youth.competition_assessments.build(discipline: :la, gender: :female)
      la_youth.competition_assessments.build(discipline: :la, gender: :male, name: "Jugend")
      la_youth.competition_assessments.build(discipline: :la, gender: :female, name: "Jugend")

      hb = build_instance.decorate
      hb.name = "Hindernisbahn-Wettkampf"
      hb.competition_assessments.build(discipline: :hb, gender: :male)
      hb.competition_assessments.build(discipline: :hb, gender: :female)

      hl = build_instance.decorate
      hl.name = "Hakenleitersteigen-Wettkampf"
      hl.competition_assessments.build(discipline: :hl, gender: :male)
      hl.competition_assessments.build(discipline: :hl, gender: :female)

      dcup = build_instance.decorate
      dcup.name = "Deutschland-Cup"
      dcup.person_tags = "U20"
      dcup.competition_assessments.build(discipline: :la, gender: :male)
      dcup.competition_assessments.build(discipline: :la, gender: :female)
      dcup.competition_assessments.build(discipline: :fs, gender: :male)
      dcup.competition_assessments.build(discipline: :fs, gender: :female)
      dcup.competition_assessments.build(discipline: :hb, gender: :male)
      dcup.competition_assessments.build(discipline: :hb, gender: :female)
      dcup.competition_assessments.build(discipline: :hl, gender: :male)
      dcup.competition_assessments.build(discipline: :hl, gender: :female)
      dcup.competition_assessments.build(discipline: :gs, gender: :female)

      empty = build_instance.decorate
      empty.name = "Leere Vorlage"
      @types = [la, la_youth, hb, hl, dcup, empty]
    end

    def show
      super

      @teams = {}
      @people = {}
      @people_count = {}
      [:female, :male].each do |gender|
        @teams[gender] = resource_instance.object.teams.gender(gender).decorate
        @people[gender] = resource_instance.object.people.gender(gender).where(team_id: nil).accessible_by(current_ability).decorate
        @people_count[gender] = resource_instance.object.people.gender(gender).where(team_id: nil).count
      end

      format = request.format.to_sym
      if format.in?([:wettkampf_manager_import, :xlsx, :pdf])
        authorize!(:export, resource_instance)
        response.headers['Content-Disposition'] = "attachment; filename=\"#{resource_instance.to_s.parameterize}.#{format}\""
        if format == :wettkampf_manager_import
          render text: resource_instance.to_serializer.to_json
        end
      end
    end

    def slug_handle
      competition = Competition.find_by_slug!(params[:slug])
      redirect_to action: :show, id: competition.id
    end

    def update
      @publishing_form = params[:publishing].present?
      super
    end

    protected

    def permitted_attributes
      attributes = [:name, :place, :date, :description, :open_at, :close_at, :person_tags, :team_tags, :slug, 
        :published, :group_score]
      attributes.push(:admin_user_id) if can?(:manage, AdminUser)
      super.permit(*attributes,
        competition_assessments_attributes: [:id, :discipline, :gender, :name, :_destroy]
      )
    end

    def build_instance
      resource_class.new(admin_user: current_admin_user)
    end
  end
end

app/controllers/comp_reg/people_controller.rb
module CompReg
  class PeopleController < CompRegController
    include CRUD::NewAction
    include CRUD::CreateAction
    include CRUD::ShowAction
    include CRUD::EditAction
    include CRUD::UpdateAction
    include CRUD::DestroyAction

    before_action :assign_instance_for_edit, only: [:edit, :participations]

    def participations
    end
    
    protected

    def permitted_attributes
      super.permit(:first_name, :last_name, :gender, :competition_id, :person_id, :team_id, :registration_order,
        tags_attributes: [:id, :_destroy, :name],
        person_assessment_participations_attributes: [ :id, :_destroy, :single_competitor_order, 
          :competition_assessment_id, :assessment_type, :group_competitor_order ]
      )
    end

    def build_instance
      @competition = Competition.find(params[:competition_id]) if params[:competition_id].present?
      @team = Team.find(params[:team_id]) if params[:team_id].present?
      resource_class.new(competition: @competition, admin_user: current_admin_user, team: @team)
    end

    def before_create_success
      if resource_instance.team.nil?
        deliver(CompetitionMailer, :new_person_registered, resource_instance)
        deliver(PersonMailer, :notification_to_creator, resource_instance)
      end
      if resource_instance.team.present?
        redirect_to action: :show, controller: :teams, id: resource_instance.team_id
      else
        redirect_to action: :participations, id: resource_instance.id
      end
    end

    def before_update_success
      if resource_instance.team.present?
        redirect_to action: :show, controller: :teams, id: resource_instance.team_id
      else
        redirect_to action: :show, controller: :competitions, id: resource_instance.competition_id
      end
    end
  
    def before_destroy_success
      if resource_instance.team.present?
        redirect_to action: :show, controller: :teams, id: resource_instance.team_id
      else
        redirect_to action: :show, controller: :competitions, id: resource_instance.competition_id
      end
    end
  end
end

app/controllers/comp_reg/teams_controller.rb
module CompReg
  class TeamsController < CompRegController
    include CRUD::NewAction
    include CRUD::CreateAction
    include CRUD::ShowAction
    include CRUD::EditAction
    include CRUD::UpdateAction
    include CRUD::DestroyAction

    before_action :assign_step_for_form, only: [:new, :create, :edit, :update]

    def show
      super

      format = request.format.to_sym
      if format.in?([:xlsx, :pdf])
        authorize!(:export, resource_instance)
        response.headers['Content-Disposition'] = "attachment; filename=\"#{resource_instance.to_s.parameterize}.#{format}\""
      end
    end

    protected

    def permitted_attributes
      super.permit(:name, :shortcut, :gender, :competition_id, :team_number, :team_leader, :street_with_house_number, 
        :postal_code, :locality, :phone_number, :email_address, :federal_state_id,
        tags_attributes: [:id, :_destroy, :name],
        team_assessment_participations_attributes: [:id, :_destroy, :competition_assessment_id],
        people_attributes: [:id, :_destroy, :first_name, :last_name, :gender, :competition_id,
          person_assessment_participations_attributes: [:id, :_destroy, :single_competitor_order, :competition_assessment_id]
        ]
      )
    end

    def build_instance
      @competition = Competition.find(params[:competition_id]) if params[:competition_id].present?
      resource_class.build_from_last(competition: @competition, admin_user: current_admin_user)
    end

    def save_instance
      if @step == 2
        super
      else
        resource_instance.valid?
        false
      end
    end

    def assign_step_for_form
      @step = params[:step].to_i
    end

    def before_destroy_success
      redirect_to controller: :competitions, id: resource_instance.competition_id, action: :show
    end

    def before_create_success
      deliver(CompetitionMailer, :new_team_registered, resource_instance)
      deliver(TeamMailer, :notification_to_creator, resource_instance)
      super
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ResourceController
  cache_actions :index, :show

  def index
    @teams = Team.with_members_and_competitions_count.decorate
    @charts = Chart::TeamOverview.new
  end

  def show
    @team_undecorared = Team.find(params[:id])
    @team = @team_undecorared.decorate
    @chart = Chart::TeamShow.new(team: @team)
    @team_members = @team_undecorared.members_with_discipline_count.map(&:decorate)
    @team_competitions = @team_undecorared.competitions_with_discipline_count.map(&:decorate)
    @group_assessments = @team_undecorared.group_assessments
    @group_disciplines = @team_undecorared.group_disciplines
    @series_round_structs = {}
    @max_cup_count = {}
    [:female, :male].each do |gender|
      @series_round_structs[gender] = Series::Round.for_team(@team.id, gender)
      @max_cup_count[gender] = @series_round_structs[gender].values.flatten.map(&:cups).map(&:count).max
    end
    @page_title = "#{@team} - Mannschaft"
  end
end

app/views/comp_reg/teams/_form.html.haml
.page-head
  %h1
    Wettkampfanmeldung
    %small= resource_instance.competition

.row
  - if resource_instance.gender.nil? || @step == 0 || errors_on?(:name, :shortcut, :gender, :team_numer, :team_leader, :street_with_house_number, :postal_code, :locality, :phone_number, :email_address)
    = render('form_step_0')
  - else
    .col-md-8
      = render('form_step_1')

app/views/comp_reg/teams/_form_step_0.html.haml
= simple_form_for(resource_instance) do |f|
  = hidden_field_tag(:step, 1)
  = f.input :competition_id, as: :hidden
  .col-md-8
    %fieldset
      %legend Allgemein
      = f.input :name
      = f.input :team_number
      = f.input :shortcut
      = f.input :gender, collection: Genderable::GENDERS.keys.map { |gender| [ g(gender), gender ]}
      = f.association :federal_state
  .col-md-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Wettkampfanmeldung
      .panel-body
        = link_to(resource_instance.competition, resource_instance.competition)

  - unless resource_instance.new_record?
    .col-md-4
      .panel.panel-default
        .panel-heading
          %h3.panel-title Entfernen?
        .panel-body
          %p Willst du die Anmeldung dieser Mannschaft entfernen?
          = link_to("Entfernen", { action: :destroy }, method: :delete, data: { confirm: "Mannschaft entfernen?" }, class: "btn btn-default btn-block btn-sm")

  .col-md-8
    %fieldset
      %legend Daten der Mannschaft
      = f.input :team_leader
      = f.input :street_with_house_number
      = f.input :postal_code
      = f.input :locality
      = f.input :phone_number
      = f.input :email_address
  .col-md-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Datenschutz
      .panel-body
        %p Die hier angegebenen Daten sind nur der Wettkampfleitung zugängig. Bitte fülle sie korrekt aus, um bei kurzfristigen Rückfragen eine Kontaktmöglichkeit zu haben.
  .col-md-8
    .pull-right
      = link_to("Abbrechen", comp_reg_competition_path(resource_instance.competition_id), class: "btn btn-default")
      = f.submit "Weiter", class: "btn btn-primary" 

app/views/comp_reg/teams/_form_step_1.html.haml
= simple_form_for(resource_instance) do |f|
  = f.input :competition_id, as: :hidden
  = f.input :name, as: :hidden
  = f.input :shortcut, as: :hidden
  = f.input :gender, as: :hidden
  = f.input :team_number, as: :hidden
  = f.input :team_leader, as: :hidden
  = f.input :street_with_house_number, as: :hidden
  = f.input :postal_code, as: :hidden
  = f.input :locality, as: :hidden
  = f.input :phone_number, as: :hidden
  = f.input :email_address,as: :hidden
  = f.input :federal_state_id, as: :hidden
  = hidden_field_tag(:step, 0)

  .row
    .col-md-9
      %table.table
        %tr
          %th Name
          %td= resource_instance.name
        %tr
          %th Abkürzung
          %td= resource_instance.shortcut
        %tr
          %th Geschlecht
          %td= resource_instance.translated_gender
    .col-md-3= f.submit "Zurück zum Namen", class: "btn btn-default"


= simple_form_for(resource_instance) do |f|
  = hidden_field_tag(:step, 2)
  = f.input :competition_id, as: :hidden
  = f.input :name, as: :hidden
  = f.input :shortcut, as: :hidden
  = f.input :gender, as: :hidden
  = f.input :team_number, as: :hidden
  = f.input :team_leader, as: :hidden
  = f.input :street_with_house_number, as: :hidden
  = f.input :postal_code, as: :hidden
  = f.input :locality, as: :hidden
  = f.input :phone_number, as: :hidden
  = f.input :email_address,as: :hidden
  = f.input :federal_state_id, as: :hidden

  - if resource_instance.competition.team_tag_list.present?
    %fieldset
      %legend Zusätzliche Angaben
      - resource_instance.competition.team_tag_list.each do |tag|
        = f.simple_fields_for :tags, (f.object.tags.find { |t| t.name == tag } || f.object.tags.new(name: tag)) do |g|
          = g.input :name, as: :hidden
          = g.input :_destroy, as: :boolean, label: tag, input_html: { checked: g.object.persisted? }, checked_value: "0", unchecked_value: "1"
          = g.input :id, as: :hidden

  - if CompReg::CompetitionAssessment.requestable_for(resource_instance).present?
    %fieldset
      %legend Wertungsgruppen auswählen
      .row
        - CompReg::CompetitionAssessment.requestable_for(resource_instance).each do |assessment|
          .col-md-5.team-assessment-participation
            = f.simple_fields_for :team_assessment_participations, resource_instance.team_assessment_participations.object.find_or_initialize_by(competition_assessment: assessment) do |g|
              %h4= assessment.decorate
              = g.input :_destroy, as: :boolean, label: 'Teilnahme', input_html: { checked: g.object.persisted? }, checked_value: "0", unchecked_value: "1"
              = g.input :competition_assessment_id, as: :hidden
  .pull-right
    = link_to("Abbrechen", comp_reg_competition_path(resource_instance.competition_id), class: "btn btn-default")
    = f.submit class: "btn btn-primary" 

app/views/comp_reg/teams/show.html.haml
.pull-right
  - if can?(:edit, resource_instance)
    = image_link_to("configure", "Mannschaft bearbeiten", { action: :edit}, image: { width: "18px" }, class: "btn btn-default btn-sm")
    = image_link_to("person-add", "Wettkämpfer hinzufügen", { controller: :people, action: :new, competition_id: resource_instance.competition_id, team_id: resource_instance.id }, image: { width: "18px" }, class: "btn btn-default btn-sm", remote: true)
= breadcrum

%table.table.table-bordered
  %tr
    %th{ colspan: 3, class: "text-center"}
      %h2 Mannschaftsanmeldung
      %h4 - Teilnehmerliste A -
  %tr
    %td{ colspan: 2, class: "text-center col-md-5" }
      %h3= resource_instance.competition.name
    %td{ class: "text-center col-md-7" }
      = discipline_image(:hb, width: 85)
      = discipline_image(:fs, width: 85)
      = discipline_image(:hl, width: 85)
      = discipline_image(:la, width: 85)
  %tr
    %th{ colspan: 2, class: "text-center col-md-5" }
      %h4= l(resource_instance.competition.date, format: :german)
    %th{ class: "text-center col-md-7" }
      %h4= "in #{resource_instance.competition.place}"
  %tr
    %th{ class: "col-md-3" } Name:
    %td{colspan: 2}= resource_instance.with_number
  %tr
    %th{ class: "col-md-3" } Wertungsgruppe:
    %td{colspan: 2}= ([g(resource_instance.gender)] + resource_instance.tag_names).join(", ")
  %tr
    %th Mannschaftsleiter:
    %td{colspan: 2}= resource_instance.team_leader
  %tr
    %th Straße, Nr.:
    %td{colspan: 2}= resource_instance.street_with_house_number
  %tr
    %th PLZ, Ort:
    %td{colspan: 2}
      = "#{resource_instance.postal_code} #{resource_instance.locality}"
      - if resource_instance.federal_state.present?
        = "/ #{resource_instance.federal_state}"
  %tr
    %th Telefon:
    %td{colspan: 2}= resource_instance.phone_number
  %tr
    %th E-Mail-Adresse:
    %td{colspan: 2}= resource_instance.email_address
  %tr
    %th Wertungen:
    %td{colspan: 2}
      = resource_instance.team_assessment_participations.map(&:competition_assessment).join(", ")
  - if resource_instance.competition.competition_assessments.for_people.present?
    %tr
      %th{ colspan: 3, class: "text-center"}
        %h2 Namensliste
        %h4 - Teilnehmerliste B -
        .pull-right
          = image_link_to("person-add", "Wettkämpfer hinzufügen", { controller: :people, action: :new, competition_id: resource_instance.competition_id, team_id: resource_instance.id }, image: { width: "18px" }, class: "btn btn-default btn-sm", remote: true)

- if resource_instance.competition.competition_assessments.for_people.present?

  #competitors.refreshable
    - if resource_instance.people.present?
      %h3 Wettkämpfer
      = count_table(resource_instance.people, class: "people-sortable-table") do |ct|
        - ct.col("Vorname", :first_name)
        - ct.col("Nachname", :last_name)
        - if resource_instance.competition.person_tag_list.present?
          - ct.col("Attribute") { |person| person.tag_names.join(", ") }
        - ct.col("", haml: true) do |row| 
          = link_to("Bearbeiten", action: :edit, controller: :people, id: row.id)
          = simple_form_for row, html: { class: "hide registration-form" } do |f|
            = f.input :registration_order, as: :hidden
        - assessments = CompReg::CompetitionAssessment.requestable_for_person(resource_instance).decorate.each do |assessment|
          - ct.col(assessment) { |row| edit_participation(row, assessment) }
        - ct.footer(class: "placeholder" ) { "" }

%hr
  - if can?(:export, resource_instance)
    .col-md-4.pull-right
      .panel.panel-default
        .panel-heading
          %h3.panel-title Export
        .panel-body
          = link_to("PDF-Format", { format: :pdf }, class: "btn btn-default btn-block btn-sm")
          = link_to("Excel-Format", { format: :xlsx }, class: "btn btn-default btn-block btn-sm")